spring:
  config:
    import: application-prod.yml
  profiles:
    active: application-prod.yml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: true

  main:
    allow-bean-definition-overriding: true
