spring:
  datasource:
    url: jdbc:${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: all
    driver-class-name: org.postgresql.Driver
    spring:
      datasource:
        url=jdbc:postgresql://hostname:port/database: